/*
 * This source file was generated by the Gradle 'init' task
 */
package processing_template;

import processing.core.PApplet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var sketch = new Sketch();
        PApplet.runSketch(new String[] { "MySketch" }, sketch);
    }
}
