/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://jogamp.org/deployment/maven")
}

// 1. Create a custom configuration just for downloading native dependencies
val nativeLibs by configurations.creating

dependencies {
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(libs.guava)
    // Core Processing
    implementation("org.processing:core:4.3.1")

    // Standard Java JogAmp Libraries
    implementation("org.jogamp.gluegen:gluegen-rt:2.5.0")
    implementation("org.jogamp.jogl:jogl-all:2.5.0")

    // Cross-platform Native Binaries
    val osClassifiers = listOf(
        "natives-macosx-universal",
        "natives-windows-amd64",
        "natives-linux-amd64"
    )
    for (classifier in osClassifiers) {
        nativeLibs("org.jogamp.gluegen:gluegen-rt:2.5.0:$classifier")
        nativeLibs("org.jogamp.jogl:jogl-all:2.5.0:$classifier")
    }
}

// 2. Automate the extraction of the native files into build/natives/
val extractNatives by tasks.registering(Sync::class) {
    val destDir = layout.buildDirectory.dir("natives")
    into(destDir)
    
    from(nativeLibs.map { zipTree(it) }) {
        include("**/*.dylib", "**/*.so", "**/*.dll")
        // Flatten the folder structure so all files sit directly in the natives directory
        eachFile { path = name } 
        includeEmptyDirs = false
    }

}

application {
    mainClass.set("processing_template.App")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
// 3. Configure the Run task to use the extracted natives
tasks.named<JavaExec>("run") {
    // Ensure extraction happens before the app runs
    dependsOn(extractNatives)
    
    // Explicitly tell Java where to find the extracted native files
    val nativesDir = layout.buildDirectory.dir("natives").get().asFile.absolutePath
    systemProperty("java.library.path", nativesDir)
    
    // Allow JOGL to hook into the native windowing system
    jvmArgs(
        "--add-exports=java.desktop/sun.awt=ALL-UNNAMED",
        "--add-exports=java.desktop/sun.java2d=ALL-UNNAMED",
        "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
        "--add-opens=java.desktop/sun.awt.opengl=ALL-UNNAMED"
    )
}

// Workaround to avoid Configuration Cache error for startScripts
tasks.named<org.gradle.api.tasks.application.CreateStartScripts>("startScripts") {
    notCompatibleWithConfigurationCache("Fails to serialize UnionFileCollection")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
